### ISSUE TITLE
API idea

### ISSUE THREAD

**Issue by edmulraney** [forgojs/forgo#28]
Hey guys,

Really minor suggestion on API style. Is there ever going to be a case where a developer needs to call `rerender(args.element)` without supplying `args.element`? If not, could the API just provide a primed `rerender`() which can be invoked without supplying `args.element`? You could provide it as a third argument to `render`, then we don't need to import `rerender` either.

i.e. your example:
```
import { rerender } from "forgo";

function SimpleTimer(initialProps) {
  let seconds = 0; // Just a regular variable, no hooks!

  return {
    render(props, args) {
      setTimeout(() => {
        seconds++;
        rerender(args.element); // rerender
      }, 1000);

      return (
        <div>
          {seconds} seconds have elapsed... {props.firstName}!
        </div>
      );
    },
  };
}
```

Becomes:

```
function SimpleTimer(initialProps) {
  let seconds = 0; // Just a regular variable, no hooks!

  return {
    render(props, args, rerender) {
      setTimeout(() => {
        seconds++;
        rerender(); 
      }, 1000);

      return (
        <div>
          {seconds} seconds have elapsed... {props.firstName}!
        </div>
      );
    },
  };
}
```

**Comment by jeswin** [comment]
Each component instance gets an args object that represents some stateful information pertaining to the instance. Such as the DOM element on which it is rendered, or its position in the list of components linked to the same DOM node. This is necessary while calling the rerender() function - and  that's what you're passing into rerender().

1) Now if by "primed", you mean that this information can be stored in the 'this' pointer somewhere - yes, that could be done. But so far we've avoided the 'this' pointer in our code. Functions just work on inputs provided explicitly. That's the coding style we've chosen for this project.

2) Now, we're API stable - there are already projects which depend on forgo. So there's a very high bar for changing the API. Unless there's a fundamental issue with it, we wouldn't be able to change it. 

3) API extension (say add a more convenient API) also has a relatively high bar. We're very conscious of library size. The current API is extensible in many ways, and there are already a bunch of libraries which take advantage of this. So, the appropriate place to add an extension to the API would be in an external lib which consumes forgo.

I'll close this now due to (2) and (3). But feel free to continue the discussion - it helps us understand how forgo is being used, and what users want. Also, I'm not entirely sure I've addressed what you're trying to ask here - so please explain.

**Comment by jeswin** [comment]
As an example of extending the API from outside, check the forgo-powertoys project. https://github.com/forgojs/forgo-powertoys

It introduces a renderElement() function which is sometimes convenient when integrating forgo with an existing app.

**Comment by jeswin** [comment]
Ah, now I see what you mean - the code above brings clarity. 

Can you post this as a separate issue (with the code example you've provided)? - I think the first three posts on this thread are offtopic.

We'll need to discuss it a bit and then take a call. I don't see it breaking anything, but we'd need to be sure if we're making the right call here.

**Comment by jeswin** [comment]
Another option could be to tack it into args itself.

```js 
function SimpleTimer(initialProps) {
  let seconds = 0; // Just a regular variable, no hooks!

  return {
    // instead of render(props, args, rerender)
    render(props, { rerender }) {
      setTimeout(() => {
        seconds++;
        rerender(); 
      }, 1000);

      return (
        <div>
          {seconds} seconds have elapsed... {props.firstName}!
        </div>
      );
    },
  };
}
```

**Comment by edmulraney** [comment]
Continued: #29
