### ISSUE TITLE
Key reordering does not preserve most components' states

### ISSUE THREAD

**Issue by spiffytech** [forgojs/forgo#33]
[Sandbox](https://codesandbox.io/s/forgo-keys-8q9po?file=/src/index.tsx)

If components in a list are reordered, the most of the moved components lose their state. I'm not totally sure what determines which ones keep/lose state, but some components that were rearranged definitely lose state.

**Comment by jeswin** [comment]
Good find!

For the benefit of other readers, let me summarize @spiffytech's example.

1. Create components m1, m2, m3, m4 and m5 each having the key prop defined. 
2. Reverse the middle three components (m4, m3 and m2). The reordering happens, but m3 and m2 are attached to newly created elements and lose state. m1, m4 and m5 use existing elements and retain state.

The reason for this is that the current algorithm only looks for elements starting from the previously located element. In this case, m4 was located at position = 4, and hence the search for m2 and m3 begins only from position = 5.  

Which is probably ok if the element doesn't have a key. But in the case of key-ed elements, the search space should include previous elements as well.

@spiffytech If you agree, I can make the change.

**Comment by spiffytech** [comment]
I recommend the change be made. It's good to keep key/state behavior consistent and avoid surprising results, it seems strictly better than losing _both_ the component and element state when key order changes, and it looks like it works out for other frameworks.

It makes sense to me that if I signal to forgo that the same component continues should be rendered, that its state would be preserved.

<hr />

I'm having trouble finding documentation for the exact consequences of detaching elements. DOM spec ([insert](https://dom.spec.whatwg.org/#concept-node-insert), [remove](https://dom.spec.whatwg.org/#concept-node-remove)) seems to defer to the [HTML spec ](https://dev.w3.org/html5/spec-LC/) for what detaching/reattaching any given element will do. I think the effects might be case-by-case per element type?

I did [some testing](https://codesandbox.io/s/charming-christian-9oetm?file=/src/index.ts). `<input>` and `<video>` states appear unaffected by reattaching, while a YouTube `<iframe>` gets reinitialized.

My impression, reading around, is that folks aren't very concerned about node detachment impacting their app (aside from people asking about cleanup). I can't find people asking about specific problems stemming from it, except for folks wondering if any automatic cleanup happens when they permanently remove an element.

A quick skim of [Morphdom's](https://github.com/patrick-steele-idem/morphdom/blob/master/src/morphdom.js#L261) and Preact's ([1](https://github.com/preactjs/preact/blob/98f130ee8695c2b4f7535205ddf02168192cdcac/src/diff/children.js#L306), [2](https://github.com/preactjs/preact/blob/98f130ee8695c2b4f7535205ddf02168192cdcac/src/diff/children.js#L231)) update logic looks like they use `replaceChild` and `insertBefore` without doing anything special to compensate for detach/reattach side effects.

I created demos in [Preact](https://codesandbox.io/s/preact-keyed-state-preservation-rihub), [React](https://codesandbox.io/s/react-keyed-state-preservation-zv5fy?file=/src/App.js), and [Vue](https://codesandbox.io/s/vue-keyed-state-preservation-f58c2), demonstrating that they all preserve component state when keys are reordered. So as far as I can tell, everyone is used to elements getting reattached and it doesn't seem to cause any significant problems.

**Comment by jeswin** [comment]
@spiffytech Thank for you the well thought out reply, and demos in three frameworks. I fully agree with what you're saying. I'll go ahead and make this change.

**Comment by jeswin** [comment]
@spiffytech This is a slightly trickier change. So this might take a couple of days more - I need to test more.

**Comment by spiffytech** [comment]
Sure thing 👍

**Comment by jeswin** [comment]
This is taking longer - requires a whole bunch of rewiring. I'm on it.

**Comment by spiffytech** [comment]
Cool, thanks for the update. 

I realized - I was focused on preserving component state, but you mentioned _element_ reordering, which seems important too. Can you clarify if the change you're working on works for just components, or also keyed non-component elements? I.e., an `<input>` with a key.

**Comment by jeswin** [comment]
Yes, the fix (whenever it's ready) should work for both. I'll add a test for that well.

**Comment by spiffytech** [comment]
Perfect - you do man!

**Comment by jeswin** [comment]
Sorry this is taking longer. It's quite a big change - hence moving very carefully.

**Comment by spiffytech** [comment]
Is there something I can do to help?

**Comment by jeswin** [comment]
Thanks, that'll be totally welcome! Let me put together a writeup first to explain the problem, and a possible solution.

**Comment by jeswin** [comment]
Let me quote the the problem again.
- Create components m1, m2, m3, m4 and m5 each having the key prop defined. Let's say, they are bound to elements e1, e2, e3, e4 and e5.
- Reverse the middle three components (to get m1, m4, m3, m2, m5). The reordering happens, but m3 and m2 are attached to newly created elements and lose state. m1, m4 and m5 use existing elements and retain state.

Reason:
- The current algorithm (implemented in `findReplacementCandidateForComponent()` and `findReplacementCandidateForElement()`) only looks for elements starting from the previously located element. In this case, m4 was located at position = 4 (e4), and hence the search for m2 and m3 begins only from position = 5 (e5).
- Now let me expand this is a bit more. When m4 in (in newly reversed order m1, m4, m3, m2, m5) is located at e4, forgo also removes nodes 2 and 3 (e2 and e3) from DOM. So they don't even exist in the DOM when we're searching for m2 and m3. 

Possible Solution:
I think it's ok to remove the nodes from DOM, but we should keep them around in a bucket of disconnected nodes. If an element does not show up, we should search this bucket of disconnected nodes as well. This bucket needs to reset for every iteration of a parent element - because we only expect to search disconnected nodes within the same parent.

It sounds like not a big deal (and maybe probably isn't), but we'll have to pass this bucket around to every function on forgo. That's because the algo works in a very recursive manner. For instance, `internalRender() -> renderArray() -> internalRender()`.

**Comment by spiffytech** [comment]
That sounds like it would work.

Would it make sense to attach the bucket to the element being iterated over? Is that advantageous vs passing a function parameter everywhere?

If we use the function parameter, maybe we could use a `WeakMap` to avoid needing to reset the bucket? If the code can be structured such that Forgo just drops all references to an element's bucket when it finishes processing an element, that's one less piece of bookkeeping to manage.

**Comment by spiffytech** [comment]
Oh, no, the `WeakMap` won't work because we'll need an explicit unmount step for discarded components,, so cleanup can't be implicit.

**Comment by jeswin** [comment]
Going to work on this. Don't have an ETA yet, though.

**Comment by jeswin** [comment]
> But I haven't looked closely enough at the code to tell if there's a natural point to create the next bucket that's not also an obvious place to reset the old one.

The buckets need to be created everytime we process an element (such as a 'div') - since the bucket should contain child nodes which are temporarily removed from that parent (the 'div' or whatever). Once we're done with the element, the bucket goes out of scope (GC'ed like any other reference). 

I don't see it so much as resetting the bucket, because we'll have a temp bucket every time we see an element. It's just an array we create, and it should go out of scope once we're done with the element.

**Comment by spiffytech** [comment]
Sounds good. Let me know if I can help.

**Comment by jeswin** [comment]
@spiffytech The master now passes the two tests for Component ordering and Element ordering. I am yet to push this out as a release given that it's a fairly significant change. 

This super important fix is wholly thanks to you. Not just in the detailed bug reports and investigation efforts, but also the solution. I was going down a very complicated path, until you suggested that we could just hold the deletedNodes bucket in the element itself. Eureka! Now the element has a deletedNodes bucket into which deleted nodes go. But these nodes are resurrected if later matched by an out of order keyed element. At that point we move the node back into the DOM, and take it off deletedNodes.

**Comment by jeswin** [comment]
Published 2.2.0

**Comment by spiffytech** [comment]
At a first glance, v2.2.1 correctly retains state across key order changes (yay!). I've spotted a few issues ([reproduction](https://codesandbox.io/s/forgo-keys-2-2-1-nes2f)).

There's something weird in the repro: on the _second_ button click, the final keyed element loses it's state. But only the second click - not the first, nor the third+.

I see an edge case: if a keyed stateful component returns a fragment containing stateful children, the children don't retain their state across rerenders. This is unexpected as an application developer, since it amounts to a component only retaining _partial_ state.

Additionally, there's a regression from Forgo 2.1: the final component in the repro retains its child's state in 2.1, but does not in 2.2.

**Comment by spiffytech** [comment]
I started writing [failing tests](https://github.com/forgojs/forgo/tree/33-followup/src/test/keyedFragmentsPreserveChildStates) to cover these cases. I pushed a commit that replicates reordering grandparents not being commutative.

I began updating the test to also catch the final grandchild changing state, but managed to trigger a runtime error with what looks like legal component code, so that's interesting.

**Comment by jeswin** [comment]
Thanks. The good news is that this code is more legible after the refactor, and hence the fixing shouldn't take as much time.

In hindsight, I should have just pushed it as an alpha.

**Comment by spiffytech** [comment]
Yeah, it's probably a good idea to start doing prerelease versions for the bigger / riskier changes.

**Comment by jeswin** [comment]
Thanks for the test. Working on it.

**Comment by spiffytech** [comment]
👍

I'd hoped to flesh out more tests for this but haven't been able to give it much attention this week.

**Comment by jeswin** [comment]
I've pushed a new commit which passes your test. Instead of doing an alpha, I've pushed a new version - because the previous one was buggy anyway. Going forward we'll do alphas.

The error was - when we resurrect nodes on account of being referenced by a keyed but re-ordered component, we need to bring back all the nodes associated with that. The mistake here was - I was resurrecting the first node, but when a component renders a fragment there might be more than one.

This was a tricky change - so I can't be sure there won't be more corner cases. :)

**Comment by spiffytech** [comment]
Everything looks good so far! I messed around a bit in the sandbox checking more complex cases, and haven't seen any problems. I'll reopen if I spot anything.

> Instead of doing an alpha, I've pushed a new version - because the previous one was buggy anyway. Going forward we'll do alphas.

Sounds good.

> The error was...

That makes total sense.

Thanks a bunch, I know you've been working hard on this.
