### ISSUE TITLE
Fragment support

### ISSUE THREAD

**Issue by jacob-ebey** [forgojs/forgo#4]
Already running into cases where fragment support is needed. A simple example is an "hoc" component where it just renders out the children property. Currently you have to wrap the children in another element like a div.

**Comment by jeswin** [comment]
Fragment support would be a good to have, certainly. 

Now this might require a bit of rework, since forgo assumes an outer/wrapper node (instead of an array of nodes) and tracks/attaches component state on that node. Now it would be possible to attach this information to the first node in a list (and mark it as say 'fragment start') - but there would be changes to be made in many places.

Definitely a feature I'd consider worth having.

**Comment by jeswin** [comment]
Forgo is now less than 2KB minified + gzipped. So whatever we do, we gotta be within the size budget as well.

**Comment by spiffytech** [comment]
In the meanwhile, you can work around lack of fragment support for many purposes with a `div` assigned the style `display: contents`, which instructs the browser to replace the element with its children. The `div` will still show up in DevTools, but for rendering and styling purposes it seems like it behaves more or less like fragment support built into the browser.

**Comment by jeswin** [comment]
Implemented in 0.0.36. There are likely to be some bugs - required quite some changes.

**Comment by jeswin** [comment]
I'll close this for now. Fragements are probably still buggy, but we'll track bugs separately.

**Comment by spiffytech** [comment]
Work's keeping me too busy to do rigorous testing, but I did a quick find/replace in my app of my `<div className="contents">` with `<>` and it looks like the new fragment support works right. Thanks!

**Comment by jeswin** [comment]
Thanks for the test, appreciate it. 

I expect it to be a bit buggy for now; a lot of the innards have changed. The earlier code worked under the assumption that every Custom Component would result in a single container DOM node, and it was a good place to hold state. Now that doesn't hold any longer - so there's some new code in there.
