### ISSUE TITLE
Infinite recursion when calling component.update() within component.mount()

### ISSUE THREAD

**Issue by chronoDave** [forgojs/forgo#70]
As the title says, forgo will throw an `too much recursion` error when using `component.update()` inside `component.update()`. Perhaps related to #62? When adding `setTimeout(() => component.update())` there's no recursion.

[Sandbox](https://codesandbox.io/s/objective-cannon-bpt3tm?file=/src/index.jsx)

I'd expect `component.mount()` to be called once; even if `component.update()` is called directly inside `component.mount()`

**Comment by spiffytech** [comment]
Ah, so your mount handler triggers a `component.update()`, and that turns into recursively remounting the component ad infinitum.

I think what's going on here is Forgo mounts the component and then [sets an internal flag](https://github.com/forgojs/forgo/blob/main/src/index.ts#L1321) saying the mount has been processed.

Because the update is triggered _during_ the first render, and because renders are synchronous, calling `handleQuery()` interrupts the render and immediately starts a second render, but crucially does so before forgo sets the `.isMounted` internal flag.

Since calling the `mount` lifecycle handler is controlled by that internal flag, the second render thinks the component hasn't been mounted and _also_ calls the `mount` handler, and then it's turtles all the way down.

---

My off-the-cuff thoughts:
1. We could set the `isMounted` flag ahead of the lifecycle hooks. That'll stop the infinite mounting.
2. We'll probably be [introducing an async update](https://github.com/forgojs/forgo/issues/46#issuecomment-1186582694) function that would also solve this use case. Basically a built-in version of your `setTimeout` snippet.
  a. The only robust, general solution to update-within-update is to asyncify the recursive updates. This issue's scenario is supposed to be terminal after first recursion, but someone will inevitably try for arbitrary-depth recursion. Though I'm not sure if a silent major hit to performance is better than a loud, immediate failure.

I'll get a PR up fixing the recursive mounts.

**Comment by spiffytech** [comment]
This has been merged and will be released in v3.2.1.
